name: sample-python
services:
  - name: sample-python
    dockerfile_path: ./Dockerfile
    github:
      repo: digitalocean/sample-python
      branch: main
      deploy_on_push: true
    routes:
      - path: /