name: sample-python
services:
  - name: sample-python
    dockerfile_path: ./Dockerfile
    github:
      repo: github.com/JTMP99/python-app
      branch: main
      deploy_on_push: true
    routes:
      - path: /